### ISSUE TITLE
Query Team: User query embedding and vector search - Research

### ISSUE THREAD

**Issue by delladoh** [Antyk45/IBM-Chatbot#25]
- Look at provided documentation.
- Spend time understanding what is required to undertake this project.
- Come back with any questions.

**Comment by nassir90** [comment]
This was initially done in the `chinaza/RAG-query` branch.

I started off with [this medium article](https://medium.com/@mutazyounes/bring-your-data-to-life-creating-a-chatbot-with-llm-langchain-vector-db-locally-on-docker-ed647e546f85) but there are some issues with it, that said, it is a good starting point for setting up a RAG model.
I don't reccomend using it directly, just read through it and then look at the code as the github as the code in the article is incomplete.

I used the `all-MiniLM-L6-v2` sentence_transformers model to generate embeddings instead of the `BAAI/bge-base-en` suggested in the medium article, which appears to be private in huggingface.

LLM memory is implemented using `langchain.memory.ChatMessageHistory`.
This is documented [here](https://python.langchain.com/docs/use_cases/chatbots/memory_management).

For vector storage and similarity search, I used [ChromaDB](https://python.langchain.com/docs/integrations/vectorstores/chroma).
ChromaDB handles vectorisation of documents automatically via the `langchain_community.vectorstores.Chroma.from_documents` function.
It is integrated with sentence transformers and supports the same model names that a sentence transformers model would take in.

Also look into the [retrieval tutorial](https://python.langchain.com/docs/use_cases/chatbots/retrieval) which uses ChromaDB.
This also covers how to implement a chain that converts the last message into a query.

Streamlit re-invokes the python script you are running each time there is a UI change.
Some things, such as chat memory need to be persisted between runs.
How to do that is documented [here](https://docs.streamlit.io/library/api-reference/performance/st.cache_resource).

This branch was tested using `LLaMa` but was not tested using `ChatGPT`, though code for using `ChatGPT` is present.
